### ISSUE TITLE
Extracted file content is garbled

### ISSUE THREAD

**Issue by ghost** [AMGarkin/BDOcrypt#1]
I use your decrypt tool to extract the file to .txt, but I got the content is garbled. I guess the problem is because the character byte.

This is the loc file I want to extract: [https://github.com/ADA-Res/Files/blob/master/languagedata_tw.loc](url)

**Comment by ghost** [comment]
I change
 `fwprintf(outFile, L"%u\t%u\t%u\t%u\t%u\t\"%s\"\r\n", strType, strID1, strID2, strID3, strID4, strBuff);` 
to 
`fwprintf(outFile, L"%u\t%u\t%u\t%u\t%u\t\"%S%s\"\r\n", strType, strID1, strID2, strID3, strID4, strBuff);`
can extract out some correct words but most parts still in garbled.

**Comment by AMGarkin** [comment]
I have downloaded original .loc file from game server and I will try to find a solution. 
However I can't read chinese characters, so I'll have to rely on Google translator. ;-)

http://dn.blackdesert.com.tw/UploadData/ads/languagedata_tw.loc

Note: Notepad++ won't open text file correctly unless it contains BOM (file must start with 2 bytes 0xFF 0xFE).
See: [GuildQuests_TW.zip](https://github.com/AMGarkin/BDOcrypt/files/2004816/GuildQuests_TW.zip)

**Comment by ghost** [comment]
Successfully tested :D
Thanks a lot.

**Comment by AMGarkin** [comment]
I have updated tool to use BOM (byte order mark). Can you please verify if it fixes this issue?

**Comment by ghost** [comment]
Verified, well done :D

I thought it was char bytes problem, and I was spending all day on the research and change of printf and fread. Didnt realize notepad++ cant open non-BOM file.

I'm not a coder or programmer and have no knowledge with C but still feel fun to do this. Now I will started learning C, and thanks your helping:)
