### ISSUE TITLE
The Touryst .loc file produces empty .txt

### ISSUE THREAD

**Issue by nanodrummer** [AMGarkin/BDOcrypt#12]
Hello! I tried decrypting the localization file from the game in CMD and PowerShell (admin mode in both) and always get this error:

PS C:\Users\USER\Downloads\BDOcrypt_v2.1\bin\x64> .\BDO_decrypt.exe localize.loc localize.txt
ERROR: Input data are corrupted or incomplete.

Is there something I can do to fix it ?

File: https://drive.google.com/file/d/1v6zjWx4OsdPHxT5lAKLGugUrLFAGDdt1/view?usp=sharing

**Comment by AMGarkin** [comment]
BDOcrypt tool is for use with completely different file then what you have linked. So there is nothing to fix.

This tool is for use with language files which game updates from this address: 
http://akamai-gamecdn.blackdesertonline.com/live001/game/language/BDOLanguage_815.zip
That 815 is version number. You can check current version number here:
http://akamai-gamecdn.blackdesertonline.com/live001/game/config/config.language.version
