### ISSUE TITLE
Decrypting languagedata_en.loc produces an empty txt file.

### ISSUE THREAD

**Issue by KaleidoDeer** [AMGarkin/BDOcrypt#7]
./BDO_decrypt.exe languagedata_en.loc languagedata_en.txt
in powershell produces the txt file thats blank. Both files being in the same directory as the exe.
V2.1 is empty while v1.0 does produce a text file with contents, its still encrypted.
Loc FIle below
https://mega.nz/#!OxEzSIRC!W04s3z140GTwS_SkdFxWTqVPI_mY9F-zHV-MO0dts_U

**Comment by AMGarkin** [comment]
I have no idea why you got empty file, v2.1 works with provided .loc file just fine. Maybe insuffcient rights for write? Try to run script as an administrator.

**Comment by KaleidoDeer** [comment]
Wow. That worked. Many thanks!
