### ISSUE TITLE
Tool can no longer decrypt .loc

### ISSUE THREAD

**Issue by YumiBDO** [AMGarkin/BDOcrypt#8]
So i've tried with multiple versions of the .loc files, EU retail, Global labs and RU, and the tool seems to no longer be able to decrypt any of the .loc files, it just spits out a still encrypted file in your chosen format

**Comment by AMGarkin** [comment]
As I no longer play BDO, its a bit hard to test this issue.
If .loc files are still at the same location on BDO update servers (latest should be http://akamai-gamecdn.blackdesertonline.com/live001/game/language/BDOLanguage_584.zip) then tool still works.
If .loc files are stored somewhere else and this is not the latest version, please send me link from where I can download it.

**Comment by YumiBDO** [comment]
Just given it a test in powershell, and seems to be working again, but still doesnt give correct outputs in CMD even when being run as admin

**Comment by Aolaike** [comment]
What environment is needed to compile .loc? Why is the file size compiled with the command zero?

**Comment by AMGarkin** [comment]
> 
> 
> What environment is needed to compile .loc? Why is the file size compiled with the command zero?

Hm, no idea what are you trying to say. I'm using this tool on Windows 10.

I have tested that it is possible to decrypt and encrypt the latest .loc files (http://akamai-gamecdn.blackdesertonline.com/live001/game/language/BDOLanguage_633.zip) using BDOcrypt v2.1 (https://github.com/AMGarkin/BDOcrypt/releases/latest).

Decrypt commandline:
```
BDO_decrypt.exe languagedata_en.loc languagedata_en.txt 
```
Encrypt:
```
BDO_encrypt.exe languagedata_en.txt languagedata_en.loc
```

As this tool working correctly, I will close this issue.
